import type { Project } from "@/types";

export const projects: Project[] = [
  {
    id: "1",
    name: "Antep fıstığının Çin pazarına girmesi",
    department: "Türkiye Operasyonları",
    status: "delayed",
    progress: 83,
    owner: "Ozan Yeşilyer",
    deadline: "2025-01-01",
  },
  {
    id: "2",
    name: "Muş Sulama Sistemi devreye alınması ve verimli kullanma",
    department: "Türkiye Operasyonları",
    status: "active",
    progress: 96,
    owner: "Recep Mergen",
    deadline: "2025-05-25",
  },
  {
    id: "3",
    name: "Yıldız Muş Arazisi Tarımsal Mekanizasyon Projesi",
    department: "Türkiye Operasyonları",
    status: "active",
    progress: 100,
    owner: "Recep Mergen",
    deadline: "2026-07-01",
  },
  {
    id: "4",
    name: "Faz 1 - Değişkenli Tarım (2024-2025 Sezonu)",
    department: "Türkiye Operasyonları",
    status: "active",
    progress: 100,
    owner: "Recep Mergen",
    deadline: "2026-12-01",
  },
  {
    id: "5",
    name: "Faz 2 - Rejeneratif Tarım (2025-2026 Sezonu)",
    department: "Türkiye Operasyonları",
    status: "delayed",
    progress: 33,
    owner: "Recep Mergen",
    deadline: "2026-12-31",
  },
  {
    id: "6",
    name: "Yem katkı ihracat arttırılması, Yem katkı ve premix ve yiy-dışı pazar genişlet.",
    department: "Türkiye Operasyonları",
    status: "delayed",
    progress: 63,
    owner: "Taylan Eğilmez",
    deadline: "2026-06-30",
  },
  {
    id: "7",
    name: "Yıldız Alparslan Anıtkır Yatırımında Arsa Edinimi",
    department: "Türkiye Operasyonları",
    status: "active",
    progress: 50,
    owner: "Recep Mergen",
    deadline: "2027-12-01",
  },
  {
    id: "8",
    name: "2 adet 8330 dwt'lik Deniz-Nehir tipi gemi inşa projesi",
    department: "Kurumsal",
    status: "active",
    progress: 75,
    owner: "İdris İlhan Telci",
    deadline: "2026-03-31",
  },
  {
    id: "9",
    name: "Bireysel Performans Yönetim Sistemi'nin kurulması",
    department: "Kurumsal",
    status: "active",
    progress: 60,
    owner: "Güven Emrah Erenler",
    deadline: "2025-11-30",
  },
  {
    id: "10",
    name: "Buğday Derin İşleme",
    department: "Kurumsal",
    status: "active",
    progress: 60,
    owner: "Suat Söbüçovalı",
    deadline: "2027-07-31",
  },
  {
    id: "11",
    name: "Çiftlik Yönetimi FarmERP",
    department: "Kurumsal",
    status: "delayed",
    progress: 0,
    owner: "Kerime İkizler",
    deadline: "2026-12-31",
  },
  {
    id: "12",
    name: "Giresun protein tesisi 2. kısım kapasite arttırım projesi",
    department: "Kurumsal",
    status: "active",
    progress: 71,
    owner: "Murat Solak",
    deadline: "2026-05-31",
  },
  {
    id: "13",
    name: "Tiryaki Sigorta Strateji & Prosedürlerinin Belirlenmesi ve Yürürlüğe Konması",
    department: "Kurumsal",
    status: "active",
    progress: 0,
    owner: "Nazlı Deniz Çetin",
    deadline: "2027-09-30",
  },
  {
    id: "14",
    name: "Grup Şirketleri Genelinde Sigorta Süreçlerinin ERP Sistemine Uyarlanması",
    department: "Kurumsal",
    status: "active",
    progress: 0,
    owner: "Nazlı Deniz Çetin",
    deadline: "2027-07-31",
  },
  {
    id: "15",
    name: "MKT Süreçlerinin Uygun Bir Şekilde Yönetimi",
    department: "Kurumsal",
    status: "active",
    progress: 60,
    owner: "Nazlı Deniz Çetin",
    deadline: "2026-06-01",
  },
  {
    id: "16",
    name: "HR&ADC Entegrasyon Projesi",
    department: "Kurumsal",
    status: "active",
    progress: 86,
    owner: "Kerime İkizler",
    deadline: "2025-08-31",
  },
  {
    id: "17",
    name: "Integrity Project",
    department: "Kurumsal",
    status: "active",
    progress: 29,
    owner: "Suat Söbüçovalı",
    deadline: "2027-12-12",
  },
  {
    id: "18",
    name: "İntranet Kurulumu - Tedarikçi belirlenmesi ve satınalma süreci",
    department: "Kurumsal",
    status: "active",
    progress: 0,
    owner: "Arzu Örsel",
    deadline: "2025-12-30",
  },
  {
    id: "19",
    name: "ITSM Projesi",
    department: "Kurumsal",
    status: "active",
    progress: 62,
    owner: "Kerime İkizler",
    deadline: "2026-03-31",
  },
  {
    id: "20",
    name: "Kazakistan Buğday Tesisi kurulumu",
    department: "Kurumsal",
    status: "active",
    progress: 50,
    owner: "Yiğit Karacı",
    deadline: "2027-06-30",
  },
  {
    id: "21",
    name: "Mamul Depo Konveyör Hattının Uzatılması projesi",
    department: "Kurumsal",
    status: "active",
    progress: 60,
    owner: "Emre Padar",
    deadline: "2025-10-31",
  },
  {
    id: "22",
    name: "Faz1 - NOLA İskele ve Depo Yenileme, Raylı Sistem Entegrasyonu",
    department: "Kurumsal",
    status: "active",
    progress: 50,
    owner: "Yiğit Karacı",
    deadline: "2026-06-15",
  },
  {
    id: "23",
    name: "Faz2 - Deodorizasyon Ünitesinin Rafineriye Dön. & Yenilenebilir Yağ Tankları",
    department: "Kurumsal",
    status: "planned",
    progress: 0,
    owner: "Yiğit Karacı",
    deadline: "2027-06-01",
  },
  {
    id: "24",
    name: "Operasyonel KPK belirleme ve BI rapor çalışması",
    department: "Kurumsal",
    status: "active",
    progress: 50,
    owner: "Burcu Gözen",
    deadline: "2026-01-01",
  },
  {
    id: "25",
    name: "Organik İzlenebilirlik Dijitalleştirme",
    department: "Kurumsal",
    status: "delayed",
    progress: 33,
    owner: "Kübra Dömbek",
    deadline: "2026-03-31",
  },
  {
    id: "26",
    name: "Pillar-2 Modeli (Yerel ve Küresel Asgari Kurumlar Vergisi müessesi)",
    department: "Kurumsal",
    status: "active",
    progress: 60,
    owner: "Devrim Aşkın",
    deadline: "2026-12-31",
  },
  {
    id: "27",
    name: "Riziko Teftiş Çalışması",
    department: "Kurumsal",
    status: "active",
    progress: 0,
    owner: "Nazlı Deniz Çetin",
    deadline: "2027-07-01",
  },
  {
    id: "28",
    name: "Sharepoint Migration",
    department: "Kurumsal",
    status: "active",
    progress: 60,
    owner: "Kerime İkizler",
    deadline: "2025-12-31",
  },
  {
    id: "29",
    name: "Sıfır İş Kazası Projesi",
    department: "Kurumsal",
    status: "active",
    progress: 78,
    owner: "Ahmet Kalkan / Halil İbrahim Öztürk",
    deadline: "2026-12-31",
  },
  {
    id: "30",
    name: "Sunrise Apollo Projesi",
    department: "Kurumsal",
    status: "delayed",
    progress: 0,
    owner: "Kerime İkizler",
    deadline: "2026-05-01",
  },
  {
    id: "31",
    name: "Sürdürülebilirlik Raporu",
    department: "Kurumsal",
    status: "active",
    progress: 86,
    owner: "Arzu Örsel",
    deadline: "2026-03-06",
  },
  {
    id: "32",
    name: "Takdir ve ödüllendirme sisteminin kurulması",
    department: "Kurumsal",
    status: "active",
    progress: 20,
    owner: "Tarkan Ferhat Yılmaz",
    deadline: "2026-06-30",
  },
  {
    id: "33",
    name: "Tiryaki Agro Global İnovasyon Merkezi (TAGIC)",
    department: "Kurumsal",
    status: "active",
    progress: 17,
    owner: "Suat Söbüçovalı",
    deadline: "2028-12-31",
  },
  {
    id: "34",
    name: "Tiryaki Dijital Akademi",
    department: "Kurumsal",
    status: "active",
    progress: 50,
    owner: "Güven Emrah Erenler",
    deadline: "2025-12-31",
  },
  {
    id: "35",
    name: "Tiryaki LTIP programının global düzeyde hayata geçirilmesi",
    department: "Kurumsal",
    status: "completed",
    progress: 100,
    owner: "Tarkan Ferhat Yılmaz",
    deadline: "2025-11-20",
  },
  {
    id: "36",
    name: "Tiryaki Yapay Zeka Projesi (TYRO HR & TRADER Agent)",
    department: "Kurumsal",
    status: "active",
    progress: 0,
    owner: "Kerime İkizler",
    deadline: "2026-03-31",
  },
  {
    id: "37",
    name: "Ukrayna orijinli organik ürünlerin üretilmesi ve tedarik edilmesi",
    department: "Kurumsal",
    status: "active",
    progress: 0,
    owner: "Raif Karacı",
    deadline: "2025-12-31",
  },
  {
    id: "38",
    name: "Uluslararası Çalışma Modelleri, Prosedür ve Sözleşmeleri",
    department: "Kurumsal",
    status: "active",
    progress: 40,
    owner: "Tarkan Ferhat Yılmaz",
    deadline: "2026-03-31",
  },
  {
    id: "39",
    name: "Faz 1: Tiryaki Agro web sitesinin güncellenmesi, Tiryaki Yem, Tiryaki Lidaş (19 adet site)",
    department: "Kurumsal",
    status: "active",
    progress: 0,
    owner: "Arzu Örsel",
    deadline: "2025-10-31",
  },
  {
    id: "40",
    name: "Faz 2: Tiryaki Irak, Afrika, Denizcilik ve diğer sitelerinin oluşturulması",
    department: "Kurumsal",
    status: "active",
    progress: 0,
    owner: "Arzu Örsel",
    deadline: "2026-04-24",
  },
  {
    id: "41",
    name: "Faz 3: Giresunport sitesinin taşınması, Yıldız sitesinin Tiryaki Tohum ve Tiryaki'ye dönüştürülmesi",
    department: "Kurumsal",
    status: "active",
    progress: 0,
    owner: "Arzu Örsel",
    deadline: "2026-05-15",
  },
  {
    id: "42",
    name: "Yetkilendirilmiş Yükümlü Sistemi Kurulumu Projesi",
    department: "Kurumsal",
    status: "active",
    progress: 67,
    owner: "Tamer Latifoğlu",
    deadline: "2025-11-30",
  },
  {
    id: "43",
    name: "Carbon Trading",
    department: "International",
    status: "active",
    progress: 29,
    owner: "Kemal Yıldız",
    deadline: "2027-04-01",
  },
  {
    id: "44",
    name: "Djibouti Port Proposal",
    department: "International",
    status: "active",
    progress: 50,
    owner: "Nevzat Çakmak",
    deadline: "2027-12-31",
  },
  {
    id: "45",
    name: "Grand Al Faw Port Project",
    department: "International",
    status: "active",
    progress: 67,
    owner: "Fatih Tiryakioğlu",
    deadline: "2025-12-31",
  },
  {
    id: "46",
    name: "Investment in Sugar Refinery Plant in Venezuela",
    department: "International",
    status: "delayed",
    progress: 17,
    owner: "Nevzat Çakmak",
    deadline: "2027-08-31",
  },
  {
    id: "47",
    name: "Iraq Agro Holding",
    department: "International",
    status: "active",
    progress: 13,
    owner: "Bahadır Açık",
    deadline: "2027-12-31",
  },
  {
    id: "48",
    name: "Organisational Alignment and Training Programme in Iraq",
    department: "International",
    status: "delayed",
    progress: 50,
    owner: "Güven Emrah Erenler",
    deadline: "2026-06-30",
  },
  {
    id: "49",
    name: "Review of African country structures and organisational apl.",
    department: "International",
    status: "active",
    progress: 20,
    owner: "Güven Emrah Erenler",
    deadline: "2024-09-30",
  },
  {
    id: "50",
    name: "Venezuela Coal Facility Project",
    department: "International",
    status: "delayed",
    progress: 0,
    owner: "Bahadır Açık",
    deadline: "2028-12-31",
  }
];
